version: "3.3"

services:
  gocdserver:
    image: gocd/gocd-server:v18.1.0
    ports:
      - "8153:8153"
      - "8154:8154"
    environment:
      - AGENT_KEY=c07c50e3-49c3-4932-afa3-b3e9b73a181e
    volumes:
      - data:/godata
      - home:/home/go
  goagent:
    image: gocd/gocd-agent-ubuntu-16.04:v18.1.0
    links:
      - gocdserver
    environment:
      - AGENT_AUTO_REGISTER_KEY=c07c50e3-49c3-4932-afa3-b3e9b73a181e
      - AGENT_AUTO_REGISTER_RESOURCES=docker
      - AGENT_AUTO_REGISTER_ENVIRONMENTS=prod
      - AGENT_AUTO_REGISTER_HOSTNAME=deploy-agent-01
volumes:
  data:
  home:
