apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etc-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: etc
    spec:
      containers:
      - name: etc2018
        image: alinaio/etc2018:2
        imagePullPolicy: Always
        ports:
        - name: nodejs-port
          containerPort: 8080

